services:
  web_green:
    extends:
      file: docker-compose.yml
      service: web
    container_name: unique-consilium-backend-web-green
    ports:
      - "127.0.0.1:8002:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-backend.settings}
    depends_on:
      - db
      - redis
